# Generated by Django 5.1.1 on 2024-10-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('movie', models.CharField(default='Source Code', max_length=100)),
                ('venue', models.CharField(default='APJ Hall', max_length=100)),
                ('time', models.CharField(default='4:30 PM', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
